conv = [
'SE EU ESTIVER ALOCADO, DEVO BATER O PONTO',
'RECEBO UM SALÁRIO ADICIONAL NAS FÉRIAS',
'QUEM LANÇA A AUSÊNCIA DE FÉRIAS',
'COMO LANÇO MINHAS AUSÊNCIAS DE FÉRIAS',
'RECEBO UM SALÁRIO ADICIONAL NAS FÉRIAS?',
'QUEM LANÇA A AUSÊNCIA DE FÉRIAS?',
'COMO LANÇO MINHAS AUSÊNCIAS DE FÉRIAS?',
'MINHAS MARCAÇÕES FORAM APAGADAS?',
'MINHAS MARCAÇÕES SUMIRAM?',
'O QUE FAÇO PARA RECEBER AS MINHAS HORAS EXTRAS?',
'MINHAS MARCAÇÕES FORAM APAGADAS?',
'ESQUECI DE BATER O PONTO, O QUE FACO?',
'ONTEM ESQUECI DE BATER O PONTO?',
'NÃO BATI, O QUE FAÇO?',
'ESQUECI DE BATER O PONTO HOJE?',
'NÃO BATI O PONTO, O QUE FAÇO?',
'QUAL É O VALOR QUE RECEBO?',
'QUANTO VOU RECEBER DE HORA EXTRA?',
'NÃO RECEBI MINHAS HORAS EXTRAS?',
'FIZ HORA EXTRA E NÃO RECEBI?',
'POR QUE NÃO RECEBI MINHAS HORAS EXTRAS?',
'POR QUE NÃO ENTROU A HORA EXTRA?',
'O QUE FAÇO PARA RECEBER AS MINHAS HORAS EXTRAS?',
'POR QUE MEU PAGAMENTO NÃO CAIU?',
'MEU PAGAMENTO NÃO ESTÁ NA MINHA CONTA?',
'NÃO CAIU?',
'MEU PAGAMENTO NÃO CAIU?',
'RECEBI MENOS?',
'NÃO RECEBI?',
'NÃO RECEBI O PAGAMENTO?',
'O MEU VALOR ESTÁ MENOR?',
'MEU SALÁRIO ESTÁ ERRADO?',
'POR QUE CAIU A MENOS?',
'QUAL A DATA QUE VOU RECEBER O BANCO DE HORAS?',
'QUANDO É FEITO O PAGAMENTO?',
'O PAGAMENTO CAI QUANDO?',
'QUANDO O PAGAMENTO CAI?',
'POR QUE NÃO ENTROU A HORA EXTRA?',
'POR QUE NÃO RECEBI MINHAS HORAS EXTRAS?',
'FIZ HORA EXTRA E NÃO RECEBI?',
'NÃO RECEBI MINHAS HORAS EXTRAS?',
'COMO VÃO REFLETIR AS HORAS DE DESLOCAMENTO?',
'HORAS DE DESLOCAMENTO É PAGO COMO HORA EXTRA OU É BANCO DE HORAS?',
'QUANTAS HORAS DE BANCO É PERMITIDO POR DIA?',
'ATÉ QUANTAS HORAS EU POSSO FAZER DE BANCO AO DIA?',
'QUAL O % DE PAGAMENTO PARA O BANCO DE HORAS?',
'COMO FUNCIONA O BANCO DE HORAS DURANTE A SEMANA?',
'Em caso de falecimento quantos dias tenho de licença?',
'Meu pai morreu quantos dias tenho de licença?',
'Minha mãe morreu  quantos dias tenho de licença?',
'Falecimento de tia abona o dia?',
'Falecimento de tio abona o dia?',
'Falecimento de vó abona o dia?',
'Falecimento de vô abano o dia?',
'Como funciona a licença de obito?',
'Quantos dias posso ficar em casa se eu me casar?',
'Como funciona a licença casamento?',
'Vou me casar ?',
'Vou casar quantos dias fico em casa?',
'Quanto vou receber de hora extra?',
'Como funciona a hora extra?',
'Onde eu aponto a hora extra?',
'Que dia eu recebo as horas extras?',
'Quando vou receber minhas horas do banco?',
'Quando vou receber as horas?',
'Qual a data de pagamento do banco?',
'Quando fecha o quadrimentre?',
'Minhas horas não foram pagas?',
'Quando paga o banco?',
'Quanto vou receber do banco?',
'Onde cadastro a minha digital?',
'Onde cadastro a biometria?',
'Quem cadastra a digital?',
'Quero cadstrar miha digital no ponto?',
'Preciso cadastrar a minha biometria. Como faço?',
'Preciso cadastrar minha digital para bater o ponto. Como faço?',
'Preciso bater o ponto como cadastra minha digital?',
'Quem devo procurar para fazer me cadastro pra bater o ponto?',
'Estou alocado preciso bater o ponto?',
'Estou alocado tenho que bater o ponto?',
'É necessário bater o ponto mesmo estando alocado?',
'Alocado marca ponto?',
'Alocado bate o ponto?',
'Alocados batem ponto eletronico?',
'Alocados precisamr efetuar a marcação de ponto?',
'Quais colaboradores precisam bater ponto?',
'Quem precisa bater o ponto?',
'Como solicito férias na GFT?',
'Quando minhas férias serão aprovadas no workspace?',
'Quando recebo as minhas férias?',
'Quando cai o pagamento das minhas férias?',
'Quando posso sair de férias?',
'Como parcelar as férias?',
'Posso parcelar as férias?',
'O que é Abono Pecuniário?',
'Posso solicitar ferias com menos de 1 ano de empresa?',
'EM MENOS DE UM ANO, CONSIGO TIRAR FÉRIAS?',
'POSSO TIRAR FÉRIAS ANTES DE UM ANO?',
'A PARTIR DE QUANDO TENHO DIREITO DE TIRAR FÉRIAS?',
'COMPLETEI UM ANO, JÁ POSSO SAIR DE FÉRIAS?',
'QUAIS OS REQUISITOS PARA TIRAR MINHAS FÉRIAS?',
'VOU TIRAR FÉRIAS PELA PRIMEIRA VEZ, COMO FAZER?',
'QUERO TIRAR FÉRIAS, COMO FUNCIONA?',
'QUANTOS DIAS DE FÉRIAS POSSO TIRAR?',
'POSSO TIRAR QUANTOS DIAS DE FÉRIAS?',
'TENHO DIREITO A QUANTOS DIAS DE FÉRIAS?',
'NA NOVA REGRA COMO POSSO DIVIDIR MINHAS FÉRIAS?',
'QUAL É A NOVA REGRA PARA DIVIDIR AS FÉRIAS?',
'POSSO DIVIDIR PS PERÍODOS DE FÉRIAS?',
'COMO POSSO FRACIONAR MINHAS FÉRIAS?',
'EM QUANTAS VEZES POSSO DIVIDIR AS FÉRIAS?',
'TENHO DIREITO À DIVIDIR MINHAS FÉRIAS?',
'QUANTAS VEZES EU POSSO DIVIDIR?',
'POSSO DIVIDIR MINHAS FÉRIAS EM QUANTAS VEZES?'

]

# conv = [
# 'Como parcelar as férias?',
# 'POSSO TIRAR FÉRIAS ANTES DE UM ANO?',
# 'A PARTIR DE QUANDO TENHO DIREITO DE TIRAR FÉRIAS?',
# 'COMPLETEI UM ANO, JÁ POSSO SAIR DE FÉRIAS?',
# 'QUAIS OS REQUISITOS PARA TIRAR MINHAS FÉRIAS?',
# 'VOU TIRAR FÉRIAS PELA PRIMEIRA VEZ, COMO FAZER?',
# 'QUERO TIRAR FÉRIAS, COMO FUNCIONA?',
# 'QUANTOS DIAS DE FÉRIAS POSSO TIRAR?',
# 'POSSO TIRAR QUANTOS DIAS DE FÉRIAS?',
# 'TENHO DIREITO A QUANTOS DIAS DE FÉRIAS?',
# 'NA NOVA REGRA COMO POSSO DIVIDIR MINHAS FÉRIAS?',
# 'QUAL É A NOVA REGRA PARA DIVIDIR AS FÉRIAS?',
# 'COMO POSSO FRACIONAR MINHAS FÉRIAS?'
#
#
# ]